"""
Gravix Layer Python SDK

Official Python client for the Gravix Layer API. Provides cloud runtime
environments and template management for AI workloads.
"""

__version__ = "0.1.68"

from .client import GravixLayer
from .types.async_client import AsyncGravixLayer
from .types.runtime import (
    Runtime,
    RuntimeFileBound,
    RuntimeList,
    RuntimeMetrics,
    RuntimeTimeoutResponse,
    RuntimeHostURL,
    FileReadResponse,
    FileWriteResponse,
    FileInfo,
    FileGetInfoResponse,
    SetPermissionsResponse,
    DirectoryCreateResponse,
    CommandRunResponse,
    CodeRunResponse,
    CodeContext,
    CodeContextDeleteResponse,
    Template,
    TemplateList,
    RuntimeKillResponse,
    Execution,
    WriteEntry,
    WriteResult,
    WriteFilesResponse,
    SSHInfo,
    SSHStatus,
    ExecutionResult,
    ExecutionError,
    ExecutionLogs,
)
from .types.templates import (
    BuildStepType,
    BuildStep,
    TemplateBuildStatusEnum,
    TemplateBuildPhase,
    TemplateBuildResponse,
    TemplateBuildStatus,
    TemplateInfo,
    TemplateSnapshot,
    TemplateListResponse,
    TemplateDeleteResponse,
    BuildLogEntry,
    TemplateBuilder,
)
from .types.agents import (
    AgentBuildStatus,
    AgentBuildPhase,
    AgentDeployStatus,
    AgentDNSStatus,
    AgentHealthStatus,
    AgentFramework,
    AgentProtocol,
    AgentSkill,
    AgentCard,
    AgentBuildRequest,
    AgentBuildResponse,
    AgentBuildStatusResponse,
    AgentDeployRequest,
    AgentDeployResponse,
    AgentEndpoint,
    AgentDestroyResponse,
)
from .resources.templates import (
    Templates,
    TemplateBuildError,
    TemplateBuildTimeoutError,
)
from .resources.agents import (
    Agents,
    AgentBuildError,
    AgentBuildTimeoutError,
)
from .resources.secret_providers import Providers
from .resources.identity import Identity
from .resources.network_policies import NetworkPolicies
from .resources.async_templates import (
    AsyncTemplates,
    AsyncTemplateBuildError,
    AsyncTemplateBuildTimeoutError,
)
from .resources.async_agents import (
    AsyncAgents,
    AsyncAgentBuildError,
    AsyncAgentBuildTimeoutError,
)
from .resources.async_secret_providers import AsyncProviders
from .resources.async_identity import AsyncIdentity
from .resources.async_network_policies import AsyncNetworkPolicies
from .types.secret_providers import (
    SecretInfo,
    SecretProvider,
    SecretProviderList,
    SecretList,
    SuccessResponse,
)
from .types.network_policies import (
    NetworkPolicy,
    NetworkPolicyList,
    NetworkPolicyRule,
    NetworkPolicyRuleList,
)
from .telemetry import (
    ATTR_LOG_IOSTREAM,
    ATTR_LOG_NAME,
    GravixLayerTelemetryConfig,
    LOG_CHANNEL_AGENT,
    LOG_CHANNEL_BUILD,
    LOG_CHANNEL_RUNTIME_CONSOLE,
    LOG_CHANNEL_RUNTIME_PTY,
    LOG_CHANNEL_RUNTIME_STDERR,
    LOG_CHANNEL_RUNTIME_STDOUT,
    configure_otel,
    configure_for_agent,
    enable_telemetry,
    genai_span,
    init_telemetry,
    log_struct,
    record_outputs,
    runtime_span,
    setup_logging,
    trace,
    traced,
)
from .types.exceptions import (
    GravixLayerError,
    GravixLayerAuthenticationError,
    GravixLayerRateLimitError,
    GravixLayerServerError,
    GravixLayerBadRequestError,
    GravixLayerConnectionError,
)

__all__ = [
    "GravixLayer",
    "AsyncGravixLayer",
    "Runtime",
    "RuntimeFileBound",
    "RuntimeList",
    "RuntimeMetrics",
    "RuntimeTimeoutResponse",
    "RuntimeHostURL",
    "RuntimeKillResponse",
    "Execution",
    "WriteEntry",
    "WriteResult",
    "WriteFilesResponse",
    "SSHInfo",
    "SSHStatus",
    "ExecutionResult",
    "ExecutionError",
    "ExecutionLogs",
    "FileReadResponse",
    "FileWriteResponse",
    "FileInfo",
    "FileGetInfoResponse",
    "SetPermissionsResponse",
    "DirectoryCreateResponse",
    "CommandRunResponse",
    "CodeRunResponse",
    "CodeContext",
    "CodeContextDeleteResponse",
    "Template",
    "TemplateList",
    "BuildStepType",
    "BuildStep",
    "TemplateBuildStatusEnum",
    "TemplateBuildPhase",
    "TemplateBuildResponse",
    "TemplateBuildStatus",
    "TemplateInfo",
    "TemplateSnapshot",
    "TemplateListResponse",
    "TemplateDeleteResponse",
    "BuildLogEntry",
    "TemplateBuilder",
    "Templates",
    "TemplateBuildError",
    "TemplateBuildTimeoutError",
    "AsyncTemplates",
    "AsyncTemplateBuildError",
    "AsyncTemplateBuildTimeoutError",
    # Agent types
    "AgentBuildStatus",
    "AgentBuildPhase",
    "AgentDeployStatus",
    "AgentDNSStatus",
    "AgentHealthStatus",
    "AgentFramework",
    "AgentProtocol",
    "AgentSkill",
    "AgentCard",
    "AgentBuildRequest",
    "AgentBuildResponse",
    "AgentBuildStatusResponse",
    "AgentDeployRequest",
    "AgentDeployResponse",
    "AgentEndpoint",
    "AgentDestroyResponse",
    # Agent resources
    "Agents",
    "AgentBuildError",
    "AgentBuildTimeoutError",
    "AsyncAgents",
    "AsyncAgentBuildError",
    "AsyncAgentBuildTimeoutError",
    # Identity providers
    "Identity",
    "AsyncIdentity",
    "Providers",
    "AsyncProviders",
    "SecretInfo",
    "SecretProvider",
    "SecretProviderList",
    "SecretList",
    "SuccessResponse",
    # Network policies
    "NetworkPolicies",
    "AsyncNetworkPolicies",
    "NetworkPolicy",
    "NetworkPolicyList",
    "NetworkPolicyRule",
    "NetworkPolicyRuleList",
    # Exceptions
    "GravixLayerError",
    "GravixLayerAuthenticationError",
    "GravixLayerRateLimitError",
    "GravixLayerServerError",
    "GravixLayerBadRequestError",
    "GravixLayerConnectionError",
    # Observability
    "GravixLayerTelemetryConfig",
    "configure_otel",
    "configure_for_agent",
    "enable_telemetry",
    "init_telemetry",
    "setup_logging",
    "log_struct",
    "LOG_CHANNEL_AGENT",
    "LOG_CHANNEL_BUILD",
    "LOG_CHANNEL_RUNTIME_STDOUT",
    "LOG_CHANNEL_RUNTIME_STDERR",
    "LOG_CHANNEL_RUNTIME_PTY",
    "LOG_CHANNEL_RUNTIME_CONSOLE",
    "ATTR_LOG_NAME",
    "ATTR_LOG_IOSTREAM",
    "traced",
    "trace",
    "genai_span",
    "runtime_span",
    "record_outputs",
]
